name: Auto approve and merge PRs by dependabot

on:
  pull_request

jobs:
  autoapprove:
    name: Auto Approve
    runs-on: ubuntu-latest
    steps:
       - name: Auto approve
         if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
         uses: hmarr/auto-approve-action@v2.0.0
         with:
          github-token: ${{ secrets.GIT_TOKEN }}
  automerge:
    name: Auto merge after successful checks
    needs: autoapprove
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        uses: pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
